# Generated by Django 4.0.3 on 2022-04-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_movie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('age', models.IntegerField()),
                ('img', models.CharField(max_length=250)),
                ('awards', models.CharField(max_length=200)),
                ('spouse', models.CharField(max_length=200)),
                ('birth_place', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='main_app.actor'),
        ),
    ]
