# Generated by Django 4.0.3 on 2022-04-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_review_alter_actor_gender_movie_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='review_content',
        ),
    ]
